language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: lint check
      node_js: node
      script: npm run lint:check

    - stage: coveralls
      node_js: node
      script: nyc npm test && nyc report --reporter=text-lcov | coveralls
